name: "Close stale issues and pull requests"
on:
    schedule:
        - cron: "0 0 * * *"

jobs:
    stale:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/stale@v6
              with:
                  stale-issue-label: "stale"
                  stale-pr-label: "stale"
                  days-before-stale: 180
                  days-before-close: 60
                  any-of-labels: "question,discussion"
